Proyecto/config/routes.rb
Rails.application.routes.draw do
  
  get 'emergencies/index'
  get 'emergencies/show'
  get 'home/index'

  root to: "emergencies#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  get 'user/:id', to: 'users#show', as: 'users_show'
end

Proyecto/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Proyecto/app/models/emergency.rb
class Emergency < ApplicationRecord
end

Proyecto/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Proyecto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Proyecto/app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  def index
    @emergs = Emergency.last(20)
  end

  def show
  end
end

Proyecto/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Proyecto/app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

Proyecto/app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

Proyecto/app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

Proyecto/app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

Proyecto/app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
    redirect_to root_path, notice: 'Cerraste sesion'
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

Proyecto/app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

Proyecto/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

Proyecto/app/helpers/application_helper.rb
module ApplicationHelper
end

Proyecto/app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

Proyecto/app/helpers/home_helper.rb
module HomeHelper
end

Proyecto/app/helpers/users_helper.rb
module UsersHelper
end

Proyecto/app/views/emergencies/index.html.erb
<div class="container text-center">
    <div class="col align-self-center">
        <h1>Emergencias</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="row align-items-start">
        <div class="col align-self-center">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th scope="col">Tipo</th>
                    <th scope="col">Lat</th>
                    <th scope="col">Lon</th>
                    <th scope="col">Location</th>
                    <th scope="col">Mensaje</th>
                    <th scope="col">Nivel</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    <% @emergs.each do |emerg| %>
                        <tr>
                            <td><%= emerg.tipo %></td>
                            <td><%= emerg.lat %></td>
                            <td><%= emerg.lon %></td>
                            <td><%= emerg.location %></td>
                            <td><%= emerg.message %></td>
                            <td><%= emerg.level %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

Proyecto/app/views/emergencies/show.html.erb
<h1>Emergencies#show</h1>
<p>Find me in app/views/emergencies/show.html.erb</p>

Proyecto/app/views/home/index.html.erb
<h1>Home#index</h1>

Proyecto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E0Arqui</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-lg">
        <a class="navbar-brand" href="/">Arqui E0</a>
        <div>
          <% if current_user %>
           
            <%= link_to "Ver Usuario" , users_show_path(current_user.id), class: "btn btn-primary"  %>
            <%= link_to "Cerrar Sesión" , destroy_user_session_path, class: "btn btn-danger" , method: :delete %>
          <% else %>
            <%= link_to "Iniciar Sesión" , new_user_session_path, class: "btn btn-primary" %>
            <%= link_to "Resgistrarse" , new_user_registration_path, class: "btn btn-primary" %>
          <% end %>          
        </div>
      </div>

    </nav>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

Proyecto/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Proyecto/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

Proyecto/app/views/users/show.html.erb
<p>
    email: <%= @user.email %>
</p>
<p>
   id:  <%= @user.id %>
</p>

<%= link_to "Editar Usuario" , edit_user_registration_path, class: "btn btn-primary" %>